version: "3.9"

services:
  db:
    image: postgres:15
    container_name: dnd-editor-db-test
    environment:
      POSTGRES_DB: dnd_editor_db
      POSTGRES_USER: dnduser
      POSTGRES_PASSWORD: dnduser
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dnduser"]
      interval: 10s
      retries: 5
      timeout: 5s

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/dnd_editor_db
      SPRING_DATASOURCE_USERNAME: dnduser
      SPRING_DATASOURCE_PASSWORD: dnduser
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/actuator/health || exit 1"]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
