apiVersion: apps/v1
kind: Deployment
metadata:
  name: dnd-editor
  labels:
    app: dnd-editor
spec:   # Запускаем 1 новый pod перед удалением старого
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dnd-editor
  template:
    metadata:
      labels:
        app: dnd-editor
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      automountServiceAccountToken: false  # отключаем автоматическое монтирование, если не нужно
      containers:
        - name: dnd-editor
          image: ghcr.io/hellgen/dnd-editor:latest
          ports:
            - containerPort: 8080

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
              ephemeral-storage: "0Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"

          livenessProbe:
            httpGet:
              path: /actuator/health  # эндпоинт health для проверки состояния
              port: 8080
            initialDelaySeconds: 300    # Задержка перед первым запросом
            periodSeconds: 60          # Интервал проверки
            timeoutSeconds: 30          # Время ожидания ответа
            failureThreshold: 3        # Количество неудачных попыток до перезапуска

          readinessProbe:
            httpGet:
              path: /actuator/health  # тот же эндпоинт для проверки готовности
              port: 8080
            initialDelaySeconds: 60    # Задержка перед первым запросом
            periodSeconds: 20          # Интервал проверки
            timeoutSeconds: 30         # Время ожидания ответа
            failureThreshold: 3