apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dnd-editor-ingress
  annotations:
    nginx.ingress.kubernetes.io/auth-response-headers: "Authorization"
    # nginx.ingress.kubernetes.io/rewrite-target: /  # если нужно переписывать путь
spec:
  rules:
    - host: 82.202.141.156  # можно заменить на домен, например example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dnd-editor
                port:
                  number: 80
  # tls:
  #   - hosts:
  #       - example.com
  #     secretName: tls-secret
