name: Deploy to k3s server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # ðŸ”¹ Ð¨Ð°Ð³ Ð»Ð¾Ð³Ð¸Ð½Ð° Ð² GHCR
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/YOUR_USERNAME/dnd-editor:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/YOUR_USERNAME/dnd-editor:latest

      - name: Save Docker image to tar
        run: |
          docker save -o dnd-editor.tar ghcr.io/YOUR_USERNAME/dnd-editor:latest

      - name: Copy tar to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "dnd-editor.tar"
          target: "~/"

      - name: Deploy on k3s
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo docker load -i ~/dnd-editor.tar
            sudo k3s kubectl rollout restart deployment backend -n default
